### ISSUE TITLE
Unable to update to latest 2.4.0 version on Expo app

### ISSUE THREAD

**Issue by matheusccastroo** [meteorrn/meteor-react-native#114]
**Describe the bug**
I'm having an issue when I'm trying to update an app (`Expo`) to the `2.4.0` release from the `2.3.0`.
The errors come from the fact that the `async-local-storage peerDependency` was changed to: `@react-native-community/async-storage`.

If I fork the package locally, revert this change (back to `@react-native-async-storage/async-storage`) and the respective requires on the `Meteor.js` file, it works without a problem.

Looking at the npm page of the `community` version, it was moved to this organization: `Async Storage has moved to new organization: https://github.com/react-native-async-storage/async-storage`, which is the one the package was using.

What's the reason for this change in specific? Is it something we can easily just revert?
I think this works on bare `react-native` flows, but I haven't checked.

**Comment by jankapunkt** [comment]
Hi @matheusccastroo sorry for late response I hat my watch settings not detailed enough to get notified by this issue.

The npm package `async-local-storage` has not been updated in 4 years and their repo is archived, see: https://www.npmjs.com/package/async-local-storage

> Looking at the npm page of the community version, it was moved to this organization: Async Storage has moved to new organization: https://github.com/react-native-async-storage/async-storage, which is the one the package was using.

You are right, it should be `@react-native-async-storage/async-storage` instead of `react-native-community/async-storage`

**Comment by jankapunkt** [comment]
Just one more question, it's actually set in `optionalDependencies` so just by installing your deps via `npm install --no-optional` or `npm ci --no-optional` should not raise any errors. Can you confirm this?

**Comment by jankapunkt** [comment]
@matheusccastroo please review #115  and let me know if this fixes your problem.

**Comment by jankapunkt** [comment]
Fixed in 2.5.0

get it via https://www.npmjs.com/package/@meteorrn/core/v/2.5.0
