### ISSUE TITLE
Option to configure NetInfo reachabilityUrl

### ISSUE THREAD

**Issue by bratelefant** [meteorrn/meteor-react-native#119]
I'd really like to include a feature to be able to change the reachability url that is used by NetInfo. NetInfo uses `https://clients3.google.com` by default.

I'm currently testing a fork of master, where I added this option. Maybe this could lead to a PR, if desired.

**Comment by jankapunkt** [comment]
Hey @bratelefant customization of such URL is highly relevant. Please add a PR, if you got something working. 👍

**Comment by bratelefant** [comment]
Ok I'll get a PR ready. Some data security guys might not like google servers to be contacted...

**Comment by bratelefant** [comment]
Which branch should the PR address?

**Comment by jankapunkt** [comment]
You're absolutely right. Please target the development branch.

**Comment by bratelefant** [comment]
Sorry, already opened a PR on the master branch after checking older PRs; but if required I could rebase to dev.

**Comment by jankapunkt** [comment]
@bratelefant no worries, I changed the base to dev
