### ISSUE TITLE
@meteorrn/core with ReactJS app

### ISSUE THREAD

**Issue by beyondtlc** [meteorrn/meteor-react-native#121]
Is it possible to meteorrn/core with a reactjs app ? 

As it is not possible for now, it will be really cool to have such capabilities.

Please help with this new feature .

Thank you very much.

**Comment by jankapunkt** [comment]
Hi @beyondtlc what is your exact goal? Do you want to connect a non-Meteor app to a Meteor server? If so, there is already [Gregivy/simpleddp](https://github.com/Gregivy/simpleddp)

You may rather inspect their package and evaluate it's features first.

I'm closing this issue for now to keep the issue list clean. If you find Gregivy/simpleddp does not suit your needs then please come back and reopen and describe your use-case in detail so we can see if it's feasible to go on with this feature request.
