### ISSUE TITLE
@react-native-community/netinfo not available on visionOS // workaround?

### ISSUE THREAD

**Issue by derwaldgeist** [meteorrn/meteor-react-native#143]
Hi, I am trying to make this package to work on the new Vision Pro glasses. However, CoreTelephony is not supported on this device, hence adding @react-native-community/netinfo breaks the build.

Would there be a chance to detect connection breakups in another way? I guess this is what the library is actually being used for, as the logs state that auto-reconnect does not work without this package.

**Comment by jankapunkt** [comment]
I was already thinking of making netinfo entirely optional / injectable because by default it contacts Google which is also not the cleanest practice imo...

However, if I just remove the netinfo it would break lots of other builds.

Maybe a good solution **for now** is to have a flag to disable netinfo (this skipping connection checks and blind-Connect to the Meteor backend). If the flag is falsy then the require of netinfo would not be called and since it's an optional dependency it should not break anything.

Would that be a viable option?

**Comment by derwaldgeist** [comment]
Thanks for your super fast response. Yes, that would make sense. Does this mean that one would have to implement a proper auto-reconnect yourself?

I am actually evaluation this as an alternative to implement a Meteor-connected app in native Swift for a visionOS, because I could not find any DDP implementation for iOS / visionOS that is actively being maintained. React native might be an alternative, since I am already using React in my Meteor web frontend.

Are you aware of any native implementation of DDP? I read on the Meteor forums that the RN version of Meteor actually uses RN's websocket implementation under the hood. I was wondering how this actually works.

**Comment by jankapunkt** [comment]
@derwaldgeist I'm actually not aware of any native DDP implementations. Regarding websocket you might scan through the react native repo and search for websocket, they have at least some c++ around there implementing some websocket stuff. If you have native websocket then youmight be able to implement DDP as it's just a protocol

**Comment by jankapunkt** [comment]
@derwaldgeist please review #145 in the meantime I create an RC for you to test

**Comment by jankapunkt** [comment]
@derwaldgeist I crated a release for you to install and test: [2.8.0-rc.0](https://github.com/meteorrn/meteor-react-native/releases/tag/v2.8.0-rc.0)

Please install via `npm install @meteorrn/core@2.8.0-rc.0` then, **important**, run `Meteor.connect` with options `{ NetInfo: null }`

**Comment by derwaldgeist** [comment]
Thanks! Will do. I have decided in the meantime that I go for the native path, for other reasons. And I did could make this native library work on visionOS:

https://github.com/engrahsanali/MeteorDDP

**Comment by jankapunkt** [comment]
Could you still please test the RC release, if it works please approve the linked pull request, so I can publish the new releases for everyone

**Comment by mattblackdev** [comment]
@jankapunkt the RC is working for me, thanks! FYI with `NetInfo: null` there's a YellowBox saying "NetInfo not installed, so DDP will not automatically reconnect".

**Comment by mattblackdev** [comment]
YW! Yes, that makes sense to me.

Great library. Excited to use it!

**Comment by derwaldgeist** [comment]
Hi, I want to try it out now. How do I use this specific version?

**Comment by jankapunkt** [comment]
> @derwaldgeist I crated a release for you to install and test: [2.8.0-rc.0](https://github.com/meteorrn/meteor-react-native/releases/tag/v2.8.0-rc.0)
> 
> Please install via `npm install @meteorrn/core@2.8.0-rc.0` then, **important**, run `Meteor.connect` with options `{ NetInfo: null }`

**Comment by derwaldgeist** [comment]
> Could you still please test the RC release, if it works please approve the linked pull request, so I can publish the new releases for everyone

Hi, I just tested it, worked for me under visionOS and iOS - great job!
