### ISSUE TITLE
Meteor.user() is sometimes undefined on resuming the app from background

### ISSUE THREAD

**Issue by bratelefant** [meteorrn/meteor-react-native#148]
On iOS I can observe that in my production / staging env, sometimes I get an undefined `Meteor.user()` after the app is resume from background. This happened using NetInfo or no NetInfo.

**Steps to reproduce the behavior:**

1. Publish Expo App eg. via TestFlight
2. Let the app suspend to background (eg. not open for several hours) while being logged in
3. resume your app and notice, that requests do not have logged in user

**Expected behavior**
User should resume the session

**Screenshots**
n/A

**Device (please complete the following information):**
iOS, iPhone 12, 15, iPad 8th gen, iOS 17, recent MeteorRN builds

**Comment by bratelefant** [comment]
I'll try to come up with a minimal reproduction of the issue. However this seems hard to reproduce.

There seems to be no `null`-checks on the method call of `User._loginWithToken`, so a `null` token value will be saved in `Data._tokenIdSaved` in any case; maybe this is could be related?

**Comment by jankapunkt** [comment]
Thanks @bratelefant I will try to get to the bottom of this

**Comment by jankapunkt** [comment]
By the way I found that `logginIn` and `loggingOut` events are not correct:

```js
  _startLoggingIn() {
    this._reactiveDict.set('_loggingIn', true);
    Data.notify('loggingIn');
  },
  _startLoggingOut() {
    User._isLoggingOut = true;
    Data.notify('loggingOut');
  },
  _endLoggingIn() {
    this._reactiveDict.set('_loggingIn', false);
    Data.notify('loggingIn');
  },
  _endLoggingOut() {
    User._isLoggingOut = false;
    Data.notify('loggingOut');
  },
```

The `_endLoggingIn` should emit `loggedInt` and `_endLoggingOut` should emit `loggedOut`

**Comment by molimauro** [comment]
still facing this issue.. @bratelefant is this working on our side now? Ty!

**Comment by bratelefant** [comment]
I'm currently quite happy with my branch fix/handle-token-login-callback 
No issues with null users here
