### ISSUE TITLE
autoConnect is broken

### ISSUE THREAD

**Issue by jankapunkt** [meteorrn/meteor-react-native#150]
**Describe the bug**
setting `autoConnect` to false will still cause an auto connect. This is, because autoConnect is implemented in DDP and Meteor.connect and while in DDP class it will respect the `autoConnect` flag, it won't in Meteor connect.

**To Reproduce**

```
Meteor.connect(url, {
  ...
  autoConnect: false,
  ...
})

const Data = Meteor.getData()
Data.ddp.on('connected', () => {
  console.debug('this should never fire')
})
```

**Expected behavior**
`autoConnect` set to false should prevent auto connect.

**Comment by jankapunkt** [comment]
@bratelefant should I implement the fix in #147 or in an own PR?

**Comment by bratelefant** [comment]
I guess it's fine if we merge this in as well. Found out that I patched this in my app manually, would like to test the complete bundle in staging as well

**Comment by jankapunkt** [comment]
keep open
