### ISSUE TITLE
callback exceed error

### ISSUE THREAD

**Issue by 1tac11** [meteorrn/meteor-react-native#160]
Hi there,

so far I am using the react-native-meteor npm package and am experiencing the issue of too many callbacks on starting the app (apparently react-native only allows for 500 callbacks at a time). Now each data-object synced from the server creates a callback and that explains the exceeding of callbacks.

Before I switch to this package (which seem to be building up on react-native-meteor), can you please tell me whether this error persisted here or can I sync more than 500 mogno-objects on starting the app?

Kind regards

**Comment by jankapunkt** [comment]
Hi @1tac11 sorry for not answering, the notification somehow slipped through my emails. Just for clrification - when exactly get 500 callbacks called - during a subscription to a publication or a method call or running observers or something else?

**Comment by 1tac11** [comment]
I actually took the original react meteor package. When first connecting on rn at subscription time I guess each object leads to a callback.

**Comment by 1tac11** [comment]
And thx for answering :)
