### ISSUE TITLE
Meteor 3.0 compatibility?

### ISSUE THREAD

**Issue by allenfuller** [meteorrn/meteor-react-native#162]
I've looked for mention of sync callbacks or other updates pertaining to Meteor's 3.0 release.

What's the best way to use this awesome package with an updated Meteor server?

**Comment by jankapunkt** [comment]
Hi @allenfuller currently I'm updating our backend to Meteor 3 and then want to stepwise migrate this lib for compatibility but also rewrite internally as there is lots of legacy code in there. Most of the library should work out of the box though.

**Comment by allenfuller** [comment]
That's phenomenal news @jankapunkt - thanks!

**Comment by adamgins** [comment]
@allenfuller @jankapunkt can you please confirm this works on Meteor v3? We've hit some issues... but I wanted to confirm if it's currently working/supported?
