### ISSUE TITLE
Remove dependency on batched updates native feature 

### ISSUE THREAD

**Issue by TheRealNate** [meteorrn/meteor-react-native#45]
In [`src/Data.js`](https://github.com/TheRealNate/meteor-react-native/blob/8f3e040b986c4402f808ec51466d36967fa70f0f/src/Data.js#L9), the batched updates feature is being used from ReactNative's shims. This dependency needs to be removed to make the package work without native (e.g. for `react-native-web`)

**Comment by da314pc** [comment]
I'll start looking into, I've been trying to make the package work with react-native-web

**Comment by da314pc** [comment]
@TheRealNate Solution I came up with,

use react-dom as a peer dependency,

Were going to have seperate imports based on if this project is web or native,

But I just forked the lib,

changed:
import {unstable_batchedUpdates} from "react-dom"

db.batchedUpdates = unstable_batchedUpdates;

There will be a webpack config issue, for Accounts.

I just used the old version of this project based on 
https://github.com/inProgress-team/react-native-meteor
