### ISSUE TITLE
On resume User is temporarily null after loggingIn is set to false

### ISSUE THREAD

**Issue by ToyboxZach** [meteorrn/meteor-react-native#58]
When reconnecting to the server the order of events is

Meteor.status().connected == true 
Meteor.loggingIn() == true 
Meteor.loggingIn() == false 
Meteor.user() gets set

When I would expect 

Meteor.status().connected == true 
Meteor.loggingIn() == true 
Meteor.user() gets set
Meteor.loggingIn() == false 

This inconsistency makes it hard to get the loading states to look right since there is a time that the user is not there but it is not loggingIn and connected. 

To work around I need to check if Meteor._userIdSaved is set to see if it's going to load it still, but it is not ideal looking at a private variable.

**Comment by TheRealNate** [comment]
Hey @ToyboxZach. Thanks for submitting this bug. I've looked at the login flow and confirmed that the issue exists. I will try and get a fix out soon.
