### ISSUE TITLE
Subscriptions Block UI thread

### ISSUE THREAD

**Issue by da314pc** [meteorrn/meteor-react-native#75]
I was have been using the old repo before migrating to yours. This is an important issue worth reviewing

https://github.com/inProgress-team/react-native-meteor/issues/301

The main benefit of this library is subscriptions. For large list or complex components, subscriptions can cause weird rendering problems.

Some content can be partially rendered.

I've tried the InteractionManage, not very helpful. React native is single threaded. Not sure if we can use a background process for this. Just an idea

**Comment by ToyboxZach** [comment]
I was having the similar problems.

I ended up having to do pretty hefty changes to make sure we aren't oversubscribing and that we only get change notifications when we want. I'm not sure how much of my changes ended up being unique to my experience, but if you are still looking for a solution this is a good starting point:

https://github.com/ToyboxZach/meteor-react-native

My app got significantly better after these changes

**Comment by TheRealNate** [comment]
@ToyboxZach, would you be open to possibly merging your changes into this repo?

**Comment by ToyboxZach** [comment]
I don't have the time to thoroughly validate it across all use cases or maintain it outside of times my product has a bug, but I can definitely open up a PR

**Comment by ToyboxZach** [comment]
Also do you have resources explaining how to run the tests? "npx mocha" doesn't seem to work for me like I would expect

**Comment by da314pc** [comment]
> I was having the similar problems.
> 
> I ended up having to do pretty hefty changes to make sure we aren't oversubscribing and that we only get change notifications when we want. I'm not sure how much of my changes ended up being unique to my experience, but if you are still looking for a solution this is a good starting point:
> 
> https://github.com/ToyboxZach/meteor-react-native
> 
> My app got significantly better after these changes

I think react native's new fabric architecture should solve this problem. 
https://medium.com/coox-tech/deep-dive-into-react-natives-new-architecture-fb67ae615ccd

From my experience, if you have a large list with lots of nested components and you try to have subscriptions like so:

const MyAppContainer = withTracker(() => {
    
    const myTodoTasks = Todos.find({completed:false}).fetch();
    const handle = Meteor.subscribe("myTodos");
    
    return {
        myTodoTasks,
        loading:!handle.ready()
    };
    
})(MyApp);

The UI thread will be blocked, the only work around for me was using meteor methods. But hopefully this will be solved.

**Comment by jankapunkt** [comment]
If I have an example component that shows how to reproduce these oversubscription then I can fast test/debug/provide a fix if possible

**Comment by da314pc** [comment]
> If I have an example component that shows how to reproduce these oversubscription then I can fast test/debug/provide a fix if possible

I'll try to get an example I had into a demo repo. This was only a problem on android If I remember correctly. But give me a couple days to get the repo back up.

**Comment by da314pc** [comment]
> If I have an example component that shows how to reproduce these oversubscription then I can fast test/debug/provide a fix if possible

Here is the best reproduction I could get.
https://github.com/da314pc/meteor_react_perf

One file, main.js 
These are the only subs that matter:
 var handler1 = Meteor.subscribe('myuserFields')   
 var handler2 = Meteor.subscribe('SubThread', subId, messageCount);
 var handler3 = Meteor.subscribe('SubThreadDescription', subId)

subthread is just a document of post, you can create a sample subscription:
the model is just in this format:
        var message = {
          _id: obj._id,
          text: obj.body,
          createdAt: obj.createdAt,
          user:{
            _id: obj.userId,
            name: obj.username,
          },
          avatar:avatar,
          image: image,
          video: video,
          attachments: attachments,
          videoImage: obj.videoPosterImage,
          reply: obj.reply,
          replyBody: obj.replyBody,
          replyattachments: obj.replyattachments,   
          replyUsername: obj.replyUsername,
          replyUserId: obj.replyUserId,
          likedByUsername: obj.likedByUsername,
          _likeCount: obj._likeCount,
          replyId: obj.replyId
        }

hope this helps
