### ISSUE TITLE
Application getting redirected to home screen(User dashboard, Initial landing page)

### ISSUE THREAD

**Issue by sujaykumardas16111993** [meteorrn/meteor-react-native#79]
We have our application built using react native(version 0.63) and meteor(version 2.5). for connection we are using @meteorrn/core.

But these are the issues that we have been facing very frequently:

1. When we go to a particular app flow through navigation all of a sudden we are redirected back to our home screen(initial screen after a small glitch: perhaps disconnection and reconnection)
2. Inside withtracker we are calling meteor.subscribe but a particular publish is being called around 6-7 times instead of once(we are able to see this in the logs from backend publish method and UI code inside withtracker callback)
3. When we navigate through a flow , going through multiple screens all of these screen components are getting saved in navigation stack. And most undesirable part is Meteor.subscribe for all of these screens are getting called multiple times even when we are not in that particular screen.

Able to reproduce this on android and iPhone

**Comment by TheRealNate** [comment]
Hi @sujaykumardas16111993, sounds like these issues are not all related to the `@meteorrn/core` package (this package has nothing to do with navigation). For your second issue where the publication gets called multiple times could your provide the code or a reproduction?
