### ISSUE TITLE
Expose EJSON in export

### ISSUE THREAD

**Issue by jankapunkt** [meteorrn/meteor-react-native#85]
We should expose `EJSON` to the client, importing this package.

**Describe the solution you'd like**

Adding `EJSON` to the export in the main js file would allow clients to define custom types that are EJSON-able and store them in a local cache, as well as sending them to the server (if defined there as such as well) via DDP.

**Describe alternatives you've considered**

Using `JSON.stringify` replacer and resolver to manually transform these but I am not sure, of an attempt to call to the Server would simply strip these from the call message, since EJSON has an internal lookup for custom types.

**Additional context**

I could add this to #83 or create an additional PR

**Comment by TheRealNate** [comment]
@jankapunkt additional PR would be preferred for cleanliness
