### ISSUE TITLE
enableVerbose is not a function

### ISSUE THREAD

**Issue by pisacode** [meteorrn/meteor-react-native#90]
**Describe the bug**
Even though I import enableVerbose, function can't be found
**To Reproduce**
1. import Meteor, { withTracker, enableVerbose } from '@meteorrn/core';
2. call enableVerbose();

**Comment by jankapunkt** [comment]
sorry for late response, `enableVerbose` is just a flag, not a function. Simply set it to true.

**Comment by jankapunkt** [comment]
sorry again, I confused it. It's a function but it's not exported the way you import it. You simply need to run

```js
import Meteor from '@meteorrn/core'

Meteor.enableVerbose()
```
