### ISSUE TITLE
Accounts.callLoginMethod not defined

### ISSUE THREAD

**Issue by sanu420** [meteorrn/meteor-react-native#95]
We needs to implement pin login feature on our meteor application, we have able to do it from meteor web application.

But from the react native app when I am calling the following function. It giving undefined error. 

 import { Accounts } from '@meteorrn/core';

  Accounts.callLoginMethod({
    methodArguments: [{
      phone: phone,
      pin: pin
    }],
    userCallback: loginCallback
  });

 Please help me to solve this issue.

**Comment by TheRealNate** [comment]
This feature doesn't exist, can anyone help add?
